import { useId } from 'react';
import { Button, Checkbox } from '../../../../core/components';
import { useCustomerFlow } from '../../context/useCustomerFlow';
import './Screen12Terms.css';

const formatRupees = (amount: number) => `₹${amount.toLocaleString('en-IN')}`;

/**
 * Customer Flow — Screen 12 (Terms & Conditions). Reference:
 * design_assets/journey-idbi-personal-loan/customer/IDBI_PLJ_S_9.png for
 * content/structure only — restyled entirely in this platform's own design
 * language, using only the shared tokens from src/index.css, not IDBI's
 * reference styling.
 *
 * Shows a scrollable, prototype-only loan-agreement summary that
 * cross-references the loan terms already generated on Screen 10, gated by
 * an "I have read and accepted…" checkbox (shared `Checkbox`). "Continue"
 * only unlocks once that box is checked, and — matching the reference's
 * actual behaviour — does *not* advance the step directly: accepting the
 * offer still requires a final OTP confirmation, so Continue simply moves
 * to Screen 13, which owns that confirmation step.
 */
function Screen12Terms() {
  const { data, updateData, goNext } = useCustomerFlow();
  const checkboxId = useId();

  const applicantName = data.preferredCardName.trim() || 'Applicant';

  const handleContinue = () => {
    if (!data.termsAccepted) return;
    goNext();
  };

  return (
    <section className="screen-terms">
      <div className="screen-terms-card">
        <p className="screen-terms-subtext">
          Please review the summary below before confirming your loan offer.
        </p>

        <div className="screen-terms-panel" tabIndex={0} aria-label="Loan agreement summary">
          <p className="screen-terms-doc-title">
            ScoreMe DLP Platform — Loan Agreement Summary (Prototype)
          </p>
          <p>
            This document is a simulated, non-binding summary generated by the
            ScoreMe DLP Platform for demonstration purposes only. It is not a
            legal loan agreement and creates no real financial obligation.
          </p>

          <p className="screen-terms-doc-section-title">1. Parties &amp; Application</p>
          <p>
            This summary is issued to <strong>{applicantName}</strong> against
            application <strong>{data.applicationId || 'the loan application generated on the previous screen'}</strong>
            {data.loanOfferSanctionDate ? (
              <>
                {' '}
                sanctioned on <strong>{data.loanOfferSanctionDate}</strong>
              </>
            ) : null}
            .
          </p>

          <p className="screen-terms-doc-section-title">2. Loan Summary</p>
          <p>
            Sanctioned Amount: <strong>{formatRupees(data.loanOfferAmount)}</strong>
            <br />
            Tenure: <strong>{data.loanOfferTenureMonths} months</strong>
            <br />
            Interest Rate: <strong>{data.loanOfferInterestRatePercent}% p.a.</strong> (reducing
            balance)
            <br />
            Monthly EMI: <strong>{formatRupees(data.loanOfferEmi)}</strong>
            <br />
            One-time Processing Fee: <strong>{formatRupees(data.loanOfferProcessingFee)}</strong>
            <br />
            Annual Percentage Rate (APR): <strong>{data.loanOfferAprPercent}% p.a.</strong>
          </p>

          <p className="screen-terms-doc-section-title">3. Repayment</p>
          <p>
            The EMI stated above will be collected on the due date each month
            for the full tenure via the primary bank account verified on the
            Income Details screen, until the loan is fully repaid. A missed or
            delayed EMI may attract additional charges and may affect the
            applicant&rsquo;s credit history.
          </p>

          <p className="screen-terms-doc-section-title">4. Prepayment &amp; Cancellation</p>
          <p>
            The applicant may cancel this loan within 3 days of disbursal by
            repaying only the principal amount, with no additional charges,
            per the Key Fact Statement shown on the Loan Offer screen. Part or
            full prepayment is otherwise permitted subject to the standard
            foreclosure terms applicable at the time.
          </p>

          <p className="screen-terms-doc-section-title">5. Data &amp; Consent</p>
          <p>
            The applicant consents to the identity, address, employment,
            income and nominee details collected earlier in this application
            being used solely to process, sanction and service this loan, and
            to be shared with regulatory or credit-bureau bodies where legally
            required.
          </p>

          <p className="screen-terms-doc-section-title">6. Grievance Redressal</p>
          <p>
            For any queries or grievances relating to this application, contact
            the support address shown on the Loan Offer screen. This
            prototype summary does not replace the formal Key Fact Statement
            or sanction letter of any real lender.
          </p>

          <p className="screen-terms-doc-section-title">7. Acceptance</p>
          <p>
            Accepting these Terms &amp; Guidelines and completing the final OTP
            confirmation on the next screen constitutes the applicant&rsquo;s
            acknowledgement and acceptance of this loan offer within this
            prototype flow.
          </p>
        </div>

        <Checkbox
          id={checkboxId}
          label="I have read and accepted the Terms & Conditions and Guidelines"
          checked={data.termsAccepted}
          onChange={(event) => updateData({ termsAccepted: event.target.checked })}
          className="screen-terms-checkbox"
        />

        <div className="screen-terms-actions">
          <Button type="button" onClick={handleContinue} disabled={!data.termsAccepted}>
            Continue
          </Button>
        </div>
      </div>
    </section>
  );
}

export default Screen12Terms;
